INSERT INTO BAND (NAME_OF_BAND, MUSIC_LABEL) VALUES ('Slipknot', 'Roadrunner Records');
INSERT INTO BAND (NAME_OF_BAND, MUSIC_LABEL) VALUES ('Ledger', 'Atlantic');
INSERT INTO BAND (NAME_OF_BAND, MUSIC_LABEL) VALUES ('Eminem', 'Shady Records');

INSERT INTO SONG (NAME, DURATION, BAND) VALUES ('All Out Life', 5.11, 'Slipknot');
INSERT INTO SONG (NAME, DURATION, BAND) VALUES ('Not Dead Yet', 3.36, 'Ledger');
INSERT INTO SONG (NAME, DURATION, BAND) VALUES ('AOV', 5.32, 'Slipknot');
INSERT INTO SONG (NAME, DURATION, BAND) VALUES ('Lucky You', 4.04, 'Eminem');

INSERT INTO SUPERUSER (LOGIN, PASSWORD, NAME, EMAIL) VALUES ('Gray', 5116951169, 'Serhii', 'sirko2097@gmail.com');
INSERT INTO SUPERUSER (LOGIN, PASSWORD, NAME) VALUES ('sadsa', 'sdwes2e23', 'Ses');
INSERT INTO SUPERUSER (LOGIN, PASSWORD, NAME) VALUES ('twister', 'password', 'Twister');

INSERT INTO PLAYLIST (SONGID, LOGINSU) VALUES (1, 'Gray');
INSERT INTO PLAYLIST (SONGID, LOGINSU) VALUES (3, 'Gray');
INSERT INTO PLAYLIST (SONGID, LOGINSU) VALUES (4, 'Gray');