CREATE OR REPLACE PACKAGE PLAY_LIST_PACKAGE AS
  TYPE T_LIST IS RECORD (
  SONG_ID NUMBER,
  LOGIN_SU VARCHAR2(30 CHAR)
  );

  TYPE T_LIST_TABLE IS TABLE OF T_LIST;

  PROCEDURE ADD_SONG(SONG_ID IN PLAYLIST.SONGID%TYPE, LOGIN_SU IN PLAYLIST.LOGINSU%TYPE);
  FUNCTION GET_PLAY_LIST
    RETURN T_LIST_TABLE PIPELINED;

END;

CREATE OR REPLACE PACKAGE BODY PLAY_LIST_PACKAGE AS
  PROCEDURE ADD_SONG(SONG_ID IN PLAYLIST.SONGID%TYPE, LOGIN_SU IN PLAYLIST.LOGINSU%TYPE) AS
    BEGIN
      INSERT INTO PLAYLIST (SONGID, LOGINSU) VALUES (SONG_ID, LOGIN_SU);
    END;

  FUNCTION GET_PLAY_LIST
    RETURN T_LIST_TABLE PIPELINED AS
    CURSOR MY_CURSOR IS
      SELECT *
      FROM PLAYLIST;
    BEGIN
      FOR REC IN MY_CURSOR
      LOOP
        PIPE ROW (REC);
      END LOOP;
    END;
END PLAY_LIST_PACKAGE;
/

select * from table (PLAY_LIST_PACKAGE.GET_PLAY_LIST())
