CREATE OR REPLACE PACKAGE USER_PACKAGE AS
  TYPE T_USER IS RECORD (
  LOGIN VARCHAR2(30 CHAR),
  PASSWORD VARCHAR2(30 CHAR),
  NAME VARCHAR2(30 CHAR),
  EMAIL VARCHAR2(30 CHAR)
  );

  TYPE T_USER_TABLE IS TABLE OF T_USER;

  FUNCTION LOG_IN(LOGIN IN SUPERUSER.LOGIN%TYPE, PASSWORD IN SUPERUSER.PASSWORD%TYPE)
    RETURN T_USER_TABLE PIPELINED;

  PROCEDURE REGISTER(LOGIN    IN SUPERUSER.LOGIN%TYPE,
                     PASSWORD IN SUPERUSER.PASSWORD%TYPE,
                     NAME     IN SUPERUSER.NAME%TYPE,
                     EMAIL    IN SUPERUSER.EMAIL%TYPE);
END;

CREATE OR REPLACE PACKAGE BODY USER_PACKAGE AS
  FUNCTION LOG_IN(LOGIN IN SUPERUSER.LOGIN%TYPE, PASSWORD IN SUPERUSER.PASSWORD%TYPE)
    RETURN T_USER_TABLE PIPELINED AS
    CURSOR MY_CUR IS
      SELECT *
      FROM SUPERUSER
      WHERE SUPERUSER.LOGIN = LOGIN
        AND SUPERUSER.PASSWORD = PASSWORD;
    BEGIN
      FOR rec IN MY_CUR
      LOOP
        pipe row (rec);
      end loop;
    END;

  PROCEDURE REGISTER(LOGIN IN SUPERUSER.LOGIN%TYPE, PASSWORD IN SUPERUSER.PASSWORD%TYPE, NAME IN SUPERUSER.NAME%TYPE,
                     EMAIL IN SUPERUSER.EMAIL%TYPE) AS
    BEGIN
      INSERT INTO SUPERUSER (LOGIN, PASSWORD, NAME, EMAIL) VALUES (LOGIN, PASSWORD, NAME, EMAIL);
    END;

END;
/

SELECT *
FROM TABLE (USER_PACKAGE.LOG_IN('Gray', 5116951169));
